### DISCUSSION TITLE
How to change color of navigation links?

### DISCUSSION THREAD

**Discussion by daso94msg** [Data-Centric-AI-Community/fg-data-profiling#1593] [Q&A]
Hi,

I want to change the appearance of my report.
I already changed the config file:
```
    style:  
          theme: null  
          primary_colors: ['#a01441', '#182173', '#4daf4a']   
    primary_colors: ['#a01441', '#182173', '#4daf4a']
```

and even the hard coded color array in the _config.py_ File.

But I can't get the "links" in the report to change their color from not being "#337ab7":

![image](https://github.com/ydataai/ydata-profiling/assets/136599398/5294e310-b24d-4702-9d6d-fa078ee7d5a3)

Any suggestions on how to solve this?

Thank you!
